### ISSUE TITLE
Shapely.Point import error

### ISSUE THREAD

**Issue by larksq** [MCZhi/DTPP#11]
the Point and LineString should be imported from shapely.geometry but not shapely?

https://github.com/MCZhi/DTPP/blob/fb63bd04127fc87a78afea4d2dcbc044fedbc5bb/planner.py#L4C1-L4C38

**Comment by MCZhi** [comment]
It seems that this is due to a different version of Shapely. Using the latest version won't parse an error.

**Comment by larksq** [comment]
That's true. Tested on 2.0.4 without errors. Thanks.
