### ISSUE TITLE
Performance over the val14 set?

### ISSUE THREAD

**Issue by larksq** [MCZhi/DTPP#12]
Hi, Thanks for the great work.

Did you run simulation benchmarks on the val14 set (from the PDM paper) for comparison? Just in case.

Thanks

val14 set: https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/script/config/common/scenario_filter/val14_split.yaml

**Comment by MCZhi** [comment]
Hi, @larksq, thank you for your interest. I didn't test on the val14 set. Because there are some flaws with the trajectory tree generator, which make it less applicable in some cases in nuPlan.

**Comment by larksq** [comment]
Thank you for your reply. Closing this issue.

**Comment by Hailan-9** [comment]
> Hi, [@larksq](https://github.com/larksq), thank you for your interest. I didn't test on the val14 set, because there are some flaws with the trajectory tree generator, which makes it less applicable in some cases in nuPlan.嗨，谢谢你的关注。我没有在 val14 集上进行测试，因为轨迹树生成器存在一些缺陷，这使得它在 nuPlan 中的某些情况下不太适用。

请问存在哪些缺陷呢？是指论文代码中轨迹树生成的方式会在某些情况下，生成的轨迹质量不高吗？
