### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by SupOne11** [MCZhi/DTPP#15]
Thanks for your work. I have some problem about visualization. 
If  running run_nuboard.py and import the nuboard file from the test_log generated by the previous test, the evaluation score is none. What are the reasons？

**Comment by MCZhi** [comment]
Hi, @SupOne11. Have you ever tried to choose scenarios to visualize in nuBoard? There should be a cog wheel in the top right corner. Click it and see if you can scenarios to visualize.

**Comment by SupOne11** [comment]
yes，I have clicked too right corner, but the scenario menu is blank. In the first time running run_simulation.py, the simulation results can be displayed normally. The config of run_nuboard should be modified？

**Comment by SupOne11** [comment]
Thank you for your reply. I now understand the problem—it is due to the incomplete test set, which causes the scene to fail to load. @MCZhi

**Comment by xining095** [comment]
I also encountered a problem where scenarios failed to load while running run_nuboard.py to visualize the existing test_log. Could you please clarify what you mean by "incomplete test set"?
