### ISSUE TITLE
Why this is query-centric?

### ISSUE THREAD

**Issue by ares89** [MCZhi/DTPP#17]
we introduce a query-centric Transformer model that performs efficient ego-conditioned motion prediction.
==========================
Why this is query-centric? Based on the source code, it appears that the system is designed with a focus on ego-centric rather than query-centric.

**Comment by MCZhi** [comment]
This concept is distinct from the query-centric encoding used in QCNet and other models. Here, we use the ego trajectory tree as the query to attend to context information, which is different from the query-centric encoding Transformer.

**Comment by ares89** [comment]
thank you for your reply.
