### ISSUE TITLE
Some problem about the calculation of the cost

### ISSUE THREAD

**Issue by BestBUCKY** [MCZhi/DTPP#19]
Dear author， thanks for your work！
I have some questions about the formula(2)-(5).
I thought the P(t) is output of CPM, so the shape is M x T x 2, it means that each branch has only one predicted trajectory. Is that right?
But in the formulas, it appears to be calculating with  multiple agents trajectory，How to obtain the predicted trajectories of multiple agents？ 
Especially in formula 5, We traversed Na other agents, how did we obtain their predicted trajectories?

Looking forward to your reply ！

**Comment by MCZhi** [comment]
Hi, @BestBUCKY, thanks for your interest. The equations or operations of the network in the paper are agent-wise. You can simply repeat the decoding operations for different agents to obtain future trajectories for multiple (Na) agents. Refer to https://github.com/MCZhi/DTPP/blob/fb63bd04127fc87a78afea4d2dcbc044fedbc5bb/scenario_tree_prediction.py#L105

**Comment by BestBUCKY** [comment]
Thanks for your reply, i got it
And in the output MLP，the agent state vector is added to the trajectory to distinguish the different agents. is that right？

**Comment by MCZhi** [comment]
Not exactly. To distinguish different agents, we add the agent state vector to the learnable query, which is used to extract information from the context encoding.

**Comment by BestBUCKY** [comment]
I understand. Thank you!
