### ISSUE TITLE
Provide pretrained model weight

### ISSUE THREAD

**Issue by zhaoy376** [MCZhi/DTPP#2]
Hi, @MCZhi ! I have already been following your project. I have already been training the model based on Nuplan-mini. Could you provide the model weights so that I can check whether I can reproduce your results ? Thanks! :)

**Comment by MCZhi** [comment]
Hi, @zhaoy376, thank you for your interest. We will release the pre-trained model shortly. Please stay tuned for further updates.

**Comment by MCZhi** [comment]
Hi, @zhaoy376. We have uploaded a base pre-trained model and testing scenarios.
