### ISSUE TITLE
could you help to explain why the GT label is 0

### ISSUE THREAD

**Issue by robotfan4** [MCZhi/DTPP#5]
Hello! @MCZhi Thank you for your great work!
Could you help to explain why the GT label is set to zero.
https://github.com/MCZhi/DTPP/blob/ee98e6de83fe2d0584ec5708ef454910dfd5b25c/train_utils.py#L73

**Comment by MCZhi** [comment]
Hi, @robotfan4, thank you for your interest. This is because, in the data processing stage, we have sorted the generated trajectories based on their FDE relative to the ground truth. The closest one is placed at the first position.

**Comment by robotfan4** [comment]
> Hi, @robotfan4, thank you for your interest. This is because, in the data processing stage, we have sorted the generated trajectories based on their FDE relative to the ground truth. The closest one is placed at the first position.

thanks for your kindly response.

**Comment by AlonZhao** [comment]
Thanks for your explanation
