### ISSUE TITLE
Excluding scenario types

### ISSUE THREAD

**Issue by wannaio** [MCZhi/DTPP#6]
Hey, cool work! I like how lightweight the model is, so you can train it on a small GPU :smiley: 

I have a question about scenarios. Was there a specific rationale behind excluding some of the scenario types that the nuPlan challenge consists of? For example if they was considered less relevant for your case and why. 

All the best!

**Comment by MCZhi** [comment]
Hi, @wannaio, thank you for your interest. Because staying still in the traffic is not of interest, so we basically exclude the scenarios types that involve being stationary in traffic and focus more on dynamic and interactive scenarios.
